"""Add asset inventory and history tables

Revision ID: 0814c418d008
Revises: 909b50d06c27
Create Date: 2026-08-21 03:52:26.451839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0814c418d008'
down_revision: Union[str, None] = '909b50d06c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_categories', sa.Column('has_id', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_categories', 'has_id')
    # ### end Alembic commands ###
