@echo off
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Running alembic migrations...
alembic upgrade head
echo Starting uvicorn...
uvicorn app.main:app --reload --port 8000
