"""update_schema_for_slots

Revision ID: 909b50d06c27
Revises: 001_initial_migration
Create Date: 2026-08-20 08:15:46.927918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909b50d06c27'
down_revision: Union[str, None] = '001_initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_categories', sa.Column('initial_stock', sa.Integer(), nullable=False))
    op.add_column('equipments', sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('equipments', 'installation_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('equipments', 'lifespan_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipments', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('equipments', 'lifespan_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipments', 'installation_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('equipments', 'placed_at')
    op.drop_column('equipment_categories', 'initial_stock')
    # ### end Alembic commands ###
