"""add ac_type and ac_asset_ids

Revision ID: e9f32fdfc996
Revises: 83c7a0ee6368
Create Date: 2026-09-14 12:45:59.926568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f32fdfc996'
down_revision: Union[str, None] = '83c7a0ee6368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_inventory', sa.Column('ac_type', sa.String(length=20), nullable=True))
    op.add_column('equipments', sa.Column('ac_in_asset_id', sa.String(length=100), nullable=True))
    op.add_column('equipments', sa.Column('ac_out_asset_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'ac_out_asset_id')
    op.drop_column('equipments', 'ac_in_asset_id')
    op.drop_column('asset_inventory', 'ac_type')
    # ### end Alembic commands ###
